"""Mobile conversion and release engine.

Three things decide whether a React Native release makes money or costs it: the
flag that decides who sees the paywall, the moment the app asks for a rating,
and the webhook pipeline that turns a payment into an entitlement exactly once.
Each has a failure that is invisible in testing and expensive in production.

  A flag rolled to everyone on a result that was noise ships a paywall that
  converts worse than the one it replaced. A rating prompt fired on launch
  burns one of the three asks Apple allows in a year on somebody who has not
  yet seen anything good. A webhook handled twice charges a card twice, and
  the customer finds that before the dashboard does.

So the statistics are computed rather than asserted, the rating gates are
enforced rather than documented, and the webhook ledger is keyed on the event
id the way a real handler has to be.

Pure logic, no Streamlit import, so this is unit testable on its own and can sit
behind the real webhook endpoint. Deterministic: nothing here reads the clock or
a random source. Bucketing is hashed from the user id, which is how a real
assignment stays stable across sessions.
"""

from __future__ import annotations

import hashlib
import math
from dataclasses import dataclass, field

ENGINE_VERSION = "1.0.0"

APP_NAME = "Reventure"


# ---------------------------------------------------------------------------
# Feature flags and bucketing
# ---------------------------------------------------------------------------

CONTROL = "control"
TREATMENT = "treatment"
VARIANTS: tuple[str, ...] = (CONTROL, TREATMENT)

FLAG_PRO_PAYWALL = "pro_paywall"


@dataclass(frozen=True)
class FeatureFlag:
    key: str
    label: str
    enabled: bool
    rollout_percent: int
    description: str

    def __post_init__(self) -> None:
        if not 0 <= self.rollout_percent <= 100:
            raise ValueError("A rollout percentage runs from 0 to 100.")


def bucket_of(user_id: str, flag_key: str) -> int:
    """Which of a hundred buckets a user falls in, stably.

    Hashed from the user id and the flag key together, so a user keeps the same
    bucket across sessions and devices, and two flags do not assign the same
    people to treatment. Random assignment per session would let one person see
    the paywall appear and disappear, which reads as a bug and poisons the
    measurement.
    """
    digest = hashlib.sha256(f"{flag_key}:{user_id}".encode("utf-8")).hexdigest()
    return int(digest[:8], 16) % 100


def variant_for(user_id: str, flag: FeatureFlag) -> str:
    if not flag.enabled:
        return CONTROL
    return TREATMENT if bucket_of(user_id, flag.key) < flag.rollout_percent \
        else CONTROL


def exposure_split(user_ids: list[str], flag: FeatureFlag) -> dict[str, int]:
    counts = {CONTROL: 0, TREATMENT: 0}
    for user_id in user_ids:
        counts[variant_for(user_id, flag)] += 1
    return counts


def sample_user_ids(count: int = 2000) -> list[str]:
    """A stable set of user ids. Generated by rule rather than randomly, so the
    exposure split is reproducible in a test and on screen."""
    if count < 0:
        raise ValueError("A user count cannot be negative.")
    return [f"usr_{index:06d}" for index in range(count)]


# ---------------------------------------------------------------------------
# A/B metrics and the statistics behind them
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class Arm:
    name: str
    users: int
    trials: int
    paid: int

    @property
    def trial_rate(self) -> float:
        return self.trials / self.users if self.users else 0.0

    @property
    def conversion_rate(self) -> float:
        """Free to paid, measured against everyone exposed rather than against
        trial starts, because a paywall that suppresses trials would otherwise
        look like an improvement."""
        return self.paid / self.users if self.users else 0.0

    def revenue(self, price: float) -> float:
        return round(self.paid * price, 2)


# The paywall that is live today, and the one behind the flag. The treatment
# converts better and starts fewer trials, which is the shape a harder paywall
# usually has.
BASELINE_CONTROL = Arm(CONTROL, users=1000, trials=214, paid=61)
BASELINE_TREATMENT = Arm(TREATMENT, users=1000, trials=176, paid=88)

MONTHLY_PRICE = 14.99


def norm_cdf(z: float) -> float:
    return 0.5 * (1.0 + math.erf(z / math.sqrt(2.0)))


Z_95 = 1.959963984540054      # two sided 95 percent
Z_POWER_80 = 0.8416212335729143


# The smallest relative lift worth shipping a paywall change for. Declared in
# advance rather than read off the result, which is the whole point: a sample
# size computed from the difference you happened to observe can never say a
# flat result is really flat.
DEFAULT_MDE = 0.15


@dataclass(frozen=True)
class TestResult:
    control: Arm
    treatment: Arm
    days_running: int
    minimum_detectable_effect: float
    z_score: float
    p_value: float
    lift: float                    # relative, treatment over control
    absolute_difference: float
    confidence_low: float
    confidence_high: float
    required_per_arm: int

    @property
    def significant(self) -> bool:
        return self.p_value < 0.05

    @property
    def powered(self) -> bool:
        return min(self.control.users, self.treatment.users) >= \
            self.required_per_arm

    @property
    def interval_excludes_zero(self) -> bool:
        return self.confidence_low > 0 or self.confidence_high < 0


def evaluate_test(control: Arm = BASELINE_CONTROL,
                  treatment: Arm = BASELINE_TREATMENT,
                  days_running: int = 14,
                  minimum_detectable_effect: float = DEFAULT_MDE) -> TestResult:
    """A two proportion z test, computed rather than asserted.

    Everything a reader would want to check is here: the pooled standard error
    behind the p value, the unpooled one behind the interval, and the sample
    size the observed difference would actually need. No library is used, so
    there is nothing to take on trust.
    """
    n1, n2 = control.users, treatment.users
    p1, p2 = control.conversion_rate, treatment.conversion_rate
    difference = p2 - p1

    if n1 == 0 or n2 == 0:
        return TestResult(control, treatment, days_running,
                          minimum_detectable_effect, 0.0, 1.0, 0.0, 0.0, 0.0,
                          0.0, 0)

    pooled = (control.paid + treatment.paid) / (n1 + n2)
    pooled_se = math.sqrt(pooled * (1 - pooled) * (1 / n1 + 1 / n2))
    z = difference / pooled_se if pooled_se else 0.0
    p_value = 2 * (1 - norm_cdf(abs(z)))

    unpooled_se = math.sqrt(p1 * (1 - p1) / n1 + p2 * (1 - p2) / n2)
    margin = Z_95 * unpooled_se

    # Sample size per arm to detect the smallest lift worth shipping, at 80
    # percent power. Computed from the declared effect rather than the observed
    # one: sizing against what you happened to measure makes a flat result look
    # like an underpowered one forever, so a test could never conclude nothing
    # happened.
    target = p1 * (1 + minimum_detectable_effect)
    mde_difference = target - p1
    if mde_difference > 0:
        average = (p1 + target) / 2
        required = ((Z_95 + Z_POWER_80) ** 2 * 2 * average * (1 - average)
                    / mde_difference ** 2)
        required_per_arm = int(math.ceil(required))
    else:
        required_per_arm = 0

    return TestResult(
        control=control, treatment=treatment, days_running=days_running,
        minimum_detectable_effect=minimum_detectable_effect,
        z_score=round(z, 4), p_value=round(p_value, 6),
        lift=round(difference / p1, 4) if p1 else 0.0,
        absolute_difference=round(difference, 6),
        confidence_low=round(difference - margin, 6),
        confidence_high=round(difference + margin, 6),
        required_per_arm=required_per_arm)


def metric_rows(result: TestResult, price: float = MONTHLY_PRICE) -> list[dict]:
    return [
        {"Metric": "Users exposed",
         "Control": f"{result.control.users:,}",
         "Pro paywall": f"{result.treatment.users:,}"},
        {"Metric": "Trials started",
         "Control": f"{result.control.trials:,} "
                    f"({result.control.trial_rate:.1%})",
         "Pro paywall": f"{result.treatment.trials:,} "
                        f"({result.treatment.trial_rate:.1%})"},
        {"Metric": "Paid conversions",
         "Control": f"{result.control.paid:,} "
                    f"({result.control.conversion_rate:.2%})",
         "Pro paywall": f"{result.treatment.paid:,} "
                        f"({result.treatment.conversion_rate:.2%})"},
        {"Metric": "Monthly revenue",
         "Control": f"{result.control.revenue(price):,.2f}",
         "Pro paywall": f"{result.treatment.revenue(price):,.2f}"},
    ]


def blended_conversion(result: TestResult, flag: FeatureFlag) -> float:
    """The conversion rate the whole audience sees at this rollout.

    Not the treatment rate. A flag at ten percent delivers a tenth of its
    effect, and a dashboard that shows the treatment rate while the flag is at
    ten percent is quietly claiming nine times the result.
    """
    share = (flag.rollout_percent / 100) if flag.enabled else 0.0
    return round(result.control.conversion_rate * (1 - share)
                 + result.treatment.conversion_rate * share, 6)


def projected_monthly_revenue(result: TestResult, flag: FeatureFlag,
                              price: float = MONTHLY_PRICE,
                              monthly_users: int = 40_000) -> float:
    if monthly_users < 0:
        raise ValueError("A user count cannot be negative.")
    return round(blended_conversion(result, flag) * monthly_users * price, 2)


# ---------------------------------------------------------------------------
# App Store rating prompt
# ---------------------------------------------------------------------------

TRIGGER_APP_LAUNCH = "App launch"
TRIGGER_ONBOARDING = "Onboarding finished"
TRIGGER_SETTINGS = "Settings opened"
TRIGGER_ERROR = "Error screen shown"
TRIGGER_DEAL_SAVED = "Saved a deal that beat its asking price"
TRIGGER_DEAL_SHARED = "Shared a deal with an agent"
TRIGGERS: tuple[str, ...] = (TRIGGER_APP_LAUNCH, TRIGGER_ONBOARDING,
                             TRIGGER_SETTINGS, TRIGGER_ERROR,
                             TRIGGER_DEAL_SAVED, TRIGGER_DEAL_SHARED)

# Only these two are a high value action: the user just got something worth
# having. Everything else is either neutral or actively a bad moment to ask.
HIGH_VALUE_TRIGGERS: tuple[str, ...] = (TRIGGER_DEAL_SAVED, TRIGGER_DEAL_SHARED)

# Apple allows at most three prompts per user per 365 days and ignores the rest
# silently, which is worse than refusing: the app believes it asked.
MAX_PROMPTS_PER_YEAR = 3
COOLDOWN_DAYS = 90
MIN_SESSIONS = 3

BLOCK_NOT_HIGH_VALUE = "Not a high value moment"
BLOCK_QUOTA = "Apple's yearly quota is spent"
BLOCK_COOLDOWN = "Inside the cooldown"
BLOCK_TOO_NEW = "The user has not used the app enough yet"
BLOCK_SAME_VERSION = "Already asked on this version"
ALLOWED = "Prompt shown"


@dataclass(frozen=True)
class RatingState:
    sessions: int = 8
    prompts_this_year: int = 0
    last_prompt_day: int | None = None
    asked_on_version: bool = False
    app_version: str = "2.4.0"


@dataclass(frozen=True)
class RatingDecision:
    trigger: str
    allowed: bool
    code: str
    reason: str
    gates: list[dict] = field(default_factory=list)


def should_prompt(trigger: str, state: RatingState = RatingState(),
                  day: int = 120) -> RatingDecision:
    """Decide whether the app may ask for a rating, and say why not.

    The gate that matters most is the first one. Apple counts an attempt even
    when the system decides not to display anything, so asking on launch spends
    one of three yearly asks on a person who has not yet seen the app do
    anything worth rating. The prompt belongs after a good outcome, not before
    one.
    """
    high_value = trigger in HIGH_VALUE_TRIGGERS
    within_cooldown = (state.last_prompt_day is not None
                       and day - state.last_prompt_day < COOLDOWN_DAYS)
    quota_spent = state.prompts_this_year >= MAX_PROMPTS_PER_YEAR
    too_new = state.sessions < MIN_SESSIONS

    gates = [
        {"Gate": "High value action", "Required": "Yes",
         "Actual": "Yes" if high_value else "No",
         "Status": "Pass" if high_value else "Block"},
        {"Gate": "Sessions before asking",
         "Required": f"{MIN_SESSIONS} or more",
         "Actual": str(state.sessions),
         "Status": "Block" if too_new else "Pass"},
        {"Gate": "Prompts used this year",
         "Required": f"Under {MAX_PROMPTS_PER_YEAR}",
         "Actual": str(state.prompts_this_year),
         "Status": "Block" if quota_spent else "Pass"},
        {"Gate": "Days since the last prompt",
         "Required": f"{COOLDOWN_DAYS} or more",
         "Actual": ("never asked" if state.last_prompt_day is None
                    else str(day - state.last_prompt_day)),
         "Status": "Block" if within_cooldown else "Pass"},
        {"Gate": "Already asked on this version", "Required": "No",
         "Actual": "Yes" if state.asked_on_version else "No",
         "Status": "Block" if state.asked_on_version else "Pass"},
    ]

    if not high_value:
        return RatingDecision(
            trigger, False, BLOCK_NOT_HIGH_VALUE,
            f"{trigger} is not a moment worth asking on. Apple counts the "
            f"attempt whether or not anything is displayed, so asking here "
            f"spends one of {MAX_PROMPTS_PER_YEAR} yearly asks on a user who "
            f"has not yet seen the app do anything for them.",
            gates)
    if too_new:
        return RatingDecision(
            trigger, False, BLOCK_TOO_NEW,
            f"Only {state.sessions} session(s) so far. Below {MIN_SESSIONS} "
            f"there is not enough experience to rate, and an early ask is what "
            f"produces a one star review about being asked.",
            gates)
    if quota_spent:
        return RatingDecision(
            trigger, False, BLOCK_QUOTA,
            f"{state.prompts_this_year} prompts already shown in the last 365 "
            f"days. Apple silently shows nothing beyond "
            f"{MAX_PROMPTS_PER_YEAR}, so the app would believe it asked and no "
            f"dialog would appear.",
            gates)
    if within_cooldown:
        return RatingDecision(
            trigger, False, BLOCK_COOLDOWN,
            f"Last asked {day - state.last_prompt_day} day(s) ago and the "
            f"cooldown is {COOLDOWN_DAYS}. Asking again this soon is how the "
            f"remaining asks get wasted on the same person.",
            gates)
    if state.asked_on_version:
        return RatingDecision(
            trigger, False, BLOCK_SAME_VERSION,
            f"Already asked on version {state.app_version}. One ask per "
            f"version keeps the prompt tied to something that changed.",
            gates)

    return RatingDecision(
        trigger, True, ALLOWED,
        f"{trigger} is a high value moment, the user has {state.sessions} "
        f"sessions, and {state.prompts_this_year} of "
        f"{MAX_PROMPTS_PER_YEAR} asks have been used. "
        f"SKStoreReviewController.requestReview is called here.",
        gates)


def record_prompt(state: RatingState, day: int) -> RatingState:
    """The state after a prompt is actually shown."""
    return RatingState(sessions=state.sessions,
                       prompts_this_year=state.prompts_this_year + 1,
                       last_prompt_day=day, asked_on_version=True,
                       app_version=state.app_version)


# ---------------------------------------------------------------------------
# Stripe subscription pipeline
# ---------------------------------------------------------------------------

EVENT_CHECKOUT_COMPLETED = "checkout.session.completed"
EVENT_SUBSCRIPTION_CREATED = "customer.subscription.created"
EVENT_SUBSCRIPTION_UPDATED = "customer.subscription.updated"
EVENT_SUBSCRIPTION_DELETED = "customer.subscription.deleted"
EVENT_INVOICE_PAID = "invoice.paid"
EVENT_INVOICE_FAILED = "invoice.payment_failed"
EVENT_TYPES: tuple[str, ...] = (
    EVENT_CHECKOUT_COMPLETED, EVENT_SUBSCRIPTION_CREATED,
    EVENT_SUBSCRIPTION_UPDATED, EVENT_SUBSCRIPTION_DELETED,
    EVENT_INVOICE_PAID, EVENT_INVOICE_FAILED,
)

ENTITLEMENT_NONE = "none"
ENTITLEMENT_TRIALING = "trialing"
ENTITLEMENT_ACTIVE = "active"
ENTITLEMENT_PAST_DUE = "past_due"
ENTITLEMENT_CANCELED = "canceled"

STATUS_AFTER: dict[str, str] = {
    EVENT_CHECKOUT_COMPLETED: ENTITLEMENT_TRIALING,
    EVENT_SUBSCRIPTION_CREATED: ENTITLEMENT_TRIALING,
    EVENT_SUBSCRIPTION_UPDATED: ENTITLEMENT_ACTIVE,
    EVENT_INVOICE_PAID: ENTITLEMENT_ACTIVE,
    EVENT_INVOICE_FAILED: ENTITLEMENT_PAST_DUE,
    EVENT_SUBSCRIPTION_DELETED: ENTITLEMENT_CANCELED,
}

APPLIED = "Applied"
DUPLICATE = "Duplicate ignored"
STALE = "Out of order, ignored"
DOUBLE_BILL_BLOCKED = "Double billing blocked"
UNKNOWN_CUSTOMER = "Unknown customer"

SOURCE_STRIPE = "Stripe checkout"
SOURCE_APPLE = "Apple Pay in app"


@dataclass(frozen=True)
class WebhookEvent:
    event_id: str            # evt_... , unique per event, repeated on retries
    type: str
    customer_id: str
    created: int             # Stripe's own ordering field
    amount_cents: int = 1499
    source: str = SOURCE_STRIPE
    apple_transaction_id: str = ""


@dataclass(frozen=True)
class LedgerEntry:
    event: WebhookEvent
    outcome: str
    status_before: str
    status_after: str
    charged_cents: int
    note: str


@dataclass
class BillingLedger:
    """What a real handler keeps: processed event ids, entitlements, and the
    Apple transaction ids already mapped to a customer."""
    seen_events: set = field(default_factory=set)
    entitlements: dict[str, dict] = field(default_factory=dict)
    apple_links: dict[str, str] = field(default_factory=dict)
    entries: list[LedgerEntry] = field(default_factory=list)

    def status_of(self, customer_id: str) -> str:
        return self.entitlements.get(customer_id, {}).get(
            "status", ENTITLEMENT_NONE)

    def charged_total(self) -> int:
        return sum(entry.charged_cents for entry in self.entries)

    def count(self, outcome: str) -> int:
        return sum(1 for entry in self.entries if entry.outcome == outcome)

    def entry_rows(self) -> list[dict]:
        return [
            {"Event id": entry.event.event_id,
             "Type": entry.event.type,
             "Customer": entry.event.customer_id,
             "Source": entry.event.source,
             "Outcome": entry.outcome,
             "Charged": f"{entry.charged_cents / 100:.2f}",
             "Entitlement": f"{entry.status_before} to {entry.status_after}"}
            for entry in self.entries
        ]

    def entitlement_rows(self) -> list[dict]:
        return [
            {"Customer": customer_id,
             "Entitlement": row.get("status", ENTITLEMENT_NONE),
             "Charged to date": f"{row.get('charged', 0) / 100:.2f}",
             "Last event": row.get("last_event", ""),
             "Apple linked": "Yes" if row.get("apple_linked") else "No"}
            for customer_id, row in sorted(self.entitlements.items())
        ]


CHARGING_EVENTS = (EVENT_INVOICE_PAID,)


def handle_event(ledger: BillingLedger, event: WebhookEvent) -> LedgerEntry:
    """Apply one webhook exactly once, and say what it did.

    Three things have to hold or somebody is charged twice. A redelivered event
    must change nothing, because Stripe retries until it gets a 2xx. An event
    that arrives after a newer one must not roll the entitlement backwards. And
    a purchase that already exists through Apple must not also be charged on
    the card, because the two systems do not know about each other.
    """
    before = ledger.status_of(event.customer_id)

    if event.event_id in ledger.seen_events:
        return _record(ledger, event, DUPLICATE, before, before, 0,
                       "Already processed. Stripe retries until the endpoint "
                       "answers with a 2xx, so the event id is the only thing "
                       "standing between a retry and a second charge.")

    row = ledger.entitlements.setdefault(
        event.customer_id, {"status": ENTITLEMENT_NONE, "charged": 0,
                            "last_created": 0, "last_event": "",
                            "apple_linked": False})

    if event.created < row["last_created"]:
        ledger.seen_events.add(event.event_id)
        return _record(ledger, event, STALE, before, before, 0,
                       f"This event was created before one already applied "
                       f"({event.created} against {row['last_created']}). "
                       f"Webhooks arrive out of order, and applying it would "
                       f"roll the entitlement backwards.")

    # Apple Pay in app purchases arrive with Apple's own transaction id. The
    # first one is linked to the customer; a second arrival of the same
    # transaction is the same purchase reaching us by another route.
    if event.apple_transaction_id:
        linked_to = ledger.apple_links.get(event.apple_transaction_id)
        if linked_to is not None and linked_to != event.customer_id:
            ledger.seen_events.add(event.event_id)
            return _record(
                ledger, event, DOUBLE_BILL_BLOCKED, before, before, 0,
                f"Apple transaction {event.apple_transaction_id} is already "
                f"linked to {linked_to}. Charging {event.customer_id} as well "
                f"would bill the same purchase twice, once through Apple and "
                f"once through Stripe.")
        if linked_to == event.customer_id and event.type in CHARGING_EVENTS:
            ledger.seen_events.add(event.event_id)
            return _record(
                ledger, event, DOUBLE_BILL_BLOCKED, before, before, 0,
                f"This subscription is already paid through Apple under "
                f"{event.apple_transaction_id}. The Stripe invoice for the "
                f"same period is not charged.")
        ledger.apple_links[event.apple_transaction_id] = event.customer_id
        row["apple_linked"] = True

    after = STATUS_AFTER[event.type]
    charged = event.amount_cents if event.type in CHARGING_EVENTS else 0

    ledger.seen_events.add(event.event_id)
    row.update({"status": after, "last_created": event.created,
                "last_event": event.event_id,
                "charged": row["charged"] + charged})

    return _record(ledger, event, APPLIED, before, after, charged,
                   f"{event.type} applied. {event.customer_id} moved from "
                   f"{before} to {after}.")


def _record(ledger: BillingLedger, event: WebhookEvent, outcome: str,
            before: str, after: str, charged: int, note: str) -> LedgerEntry:
    entry = LedgerEntry(event=event, outcome=outcome, status_before=before,
                        status_after=after, charged_cents=charged, note=note)
    ledger.entries.append(entry)
    return entry


CUSTOMER_WEB = "cus_Q1web8823"
CUSTOMER_APPLE = "cus_Q1ios4471"
APPLE_TRANSACTION = "1000000982374615"


def sample_webhooks() -> tuple[WebhookEvent, ...]:
    """A realistic delivery, including the three cases a handler is judged on:
    a retry, an out of order event and the same purchase arriving twice."""
    return (
        WebhookEvent("evt_1PaA01", EVENT_CHECKOUT_COMPLETED, CUSTOMER_WEB, 100),
        WebhookEvent("evt_1PaA02", EVENT_SUBSCRIPTION_CREATED, CUSTOMER_WEB, 101),
        WebhookEvent("evt_1PaA03", EVENT_INVOICE_PAID, CUSTOMER_WEB, 102),
        # Stripe did not get a 2xx in time and sent it again.
        WebhookEvent("evt_1PaA03", EVENT_INVOICE_PAID, CUSTOMER_WEB, 102),
        # An older update arriving late.
        WebhookEvent("evt_1PaA04", EVENT_SUBSCRIPTION_UPDATED, CUSTOMER_WEB, 99),
        # The in app purchase, then the same purchase reaching Stripe.
        WebhookEvent("evt_1PaB01", EVENT_SUBSCRIPTION_CREATED, CUSTOMER_APPLE,
                     200, source=SOURCE_APPLE,
                     apple_transaction_id=APPLE_TRANSACTION),
        WebhookEvent("evt_1PaB02", EVENT_INVOICE_PAID, CUSTOMER_APPLE, 201,
                     source=SOURCE_APPLE,
                     apple_transaction_id=APPLE_TRANSACTION),
    )


def replay(events: tuple[WebhookEvent, ...],
           ledger: BillingLedger | None = None) -> BillingLedger:
    target = ledger or BillingLedger()
    for event in events:
        handle_event(target, event)
    return target


# ---------------------------------------------------------------------------
# The recommendation
# ---------------------------------------------------------------------------

SHIP = "Ship it"
HOLD = "Hold, no effect found"
MORE_DATA = "Keep running, not enough data"
ROLL_BACK = "Roll it back"
TOO_EARLY = "Too early to read"

MIN_DAYS = 7


@dataclass(frozen=True)
class Recommendation:
    verdict: str
    confident: bool
    headline: str
    reasoning: list[str]
    next_step: str
    monthly_revenue_delta: float


def recommend(result: TestResult, flag: FeatureFlag,
              price: float = MONTHLY_PRICE,
              monthly_users: int = 40_000) -> Recommendation:
    """Turn the statistics into a decision, with the reasoning shown.

    Computed from the numbers rather than generated, deliberately. A real
    deployment would hand these same figures to Claude for the write up; doing
    the arithmetic here means the recommendation cannot contradict the table it
    is describing, which is the failure mode that matters when somebody ships
    on the strength of a paragraph.
    """
    control, treatment = result.control, result.treatment
    per_user_delta = (treatment.conversion_rate - control.conversion_rate) * price
    revenue_delta = round(per_user_delta * monthly_users, 2)

    reasoning = [
        f"Control converted {control.paid} of {control.users} exposed users "
        f"at {control.conversion_rate:.2%}. The Pro paywall converted "
        f"{treatment.paid} of {treatment.users} at "
        f"{treatment.conversion_rate:.2%}.",
        f"That is a relative lift of {result.lift:+.1%}, an absolute "
        f"difference of {result.absolute_difference:+.2%}.",
        f"Two proportion z test: z of {result.z_score:.2f}, p of "
        f"{result.p_value:.4f}. The 95 percent interval on the difference "
        f"runs {result.confidence_low:+.2%} to {result.confidence_high:+.2%}.",
        f"Detecting a {result.minimum_detectable_effect:.0%} relative lift at "
        f"80 percent power needs about {result.required_per_arm:,} users per "
        f"arm, and the smaller arm has "
        f"{min(control.users, treatment.users):,}.",
        f"Trial starts moved from {control.trial_rate:.1%} to "
        f"{treatment.trial_rate:.1%}, so the paywall is filtering rather than "
        f"widening the funnel.",
    ]

    if result.days_running < MIN_DAYS:
        return Recommendation(
            TOO_EARLY, False,
            f"Only {result.days_running} day(s) of data. Weekday and weekend "
            f"buyers behave differently, so a test read before a full week is "
            f"reading the calendar rather than the paywall.",
            reasoning,
            f"Leave the flag at {flag.rollout_percent} percent and read it "
            f"again after {MIN_DAYS} days.",
            revenue_delta)

    if result.significant and result.absolute_difference > 0:
        if not result.powered:
            reasoning.append(
                "The arms are smaller than the planning calculation wanted. "
                "The result still stands, and the measured lift is probably "
                "flattering: a difference that clears significance early tends "
                "to be the high end of the range. Plan on the low end of the "
                "interval rather than the point estimate.")
        return Recommendation(
            SHIP, True,
            f"The Pro paywall wins. p of {result.p_value:.4f} against a "
            f"{result.lift:+.1%} lift, and the whole confidence interval sits "
            f"above zero.",
            reasoning,
            f"Raise the flag from {flag.rollout_percent} to 50 percent for a "
            f"day, watch for crashes and refunds rather than conversion, then "
            f"go to 100. Worth about {revenue_delta:,.0f} a month at "
            f"{monthly_users:,} users.",
            revenue_delta)

    if result.significant and result.absolute_difference < 0:
        return Recommendation(
            ROLL_BACK, True,
            f"The Pro paywall converts worse, and the result is real: p of "
            f"{result.p_value:.4f} on a {result.lift:+.1%} change.",
            reasoning,
            f"Set the flag to 0 percent now. Leaving it costs about "
            f"{abs(revenue_delta):,.0f} a month.",
            revenue_delta)

    if not result.powered:
        shortfall = max(0, result.required_per_arm
                        - min(control.users, treatment.users))
        return Recommendation(
            MORE_DATA, False,
            f"No result yet. p of {result.p_value:.4f}, and the arms are "
            f"smaller than this difference needs.",
            reasoning,
            f"Keep the flag where it is and collect roughly {shortfall:,} more "
            f"users per arm before reading it again. Shipping on this would be "
            f"shipping on noise.",
            revenue_delta)

    return Recommendation(
        HOLD, True,
        f"The two paywalls perform the same. p of {result.p_value:.4f} with "
        f"arms large enough to have found a real difference.",
        reasoning,
        "Keep the current paywall. A change that does nothing still costs "
        "review time and a migration, so it is not free to ship.",
        revenue_delta)
